version: '3'

networks:
  httpmq-go-test:
    driver: bridge

services:
  dev-nats:
    image: nats:2.6.2
    hostname: dev-nats
    expose:
      - 4222
    networks:
      - httpmq-go-test
    volumes:
      - ./docker/test_nats.conf:/nats-server.conf

  httpmq-mgmt:
    image: alwitt/httpmq:0.3.2-rc.1
    hostname: management
    command:
      - management
    ports:
      - 127.0.0.1:4000:3000
    networks:
      - httpmq-go-test
    environment:
      LOG_LEVEL: info
      CONFIG_FILE: /httpmq.yaml
    stop_grace_period: 30s
    stop_signal: SIGINT
    volumes:
      - ./docker/test_httpmq.yaml:/httpmq.yaml

  httpmq-data:
    image: alwitt/httpmq:0.3.2-rc.1
    hostname: dataplane
    command:
      - dataplane
    ports:
      - 127.0.0.1:4001:3000
    networks:
      - httpmq-go-test
    environment:
      LOG_LEVEL: info
      CONFIG_FILE: /httpmq.yaml
    stop_grace_period: 30s
    stop_signal: SIGINT
    volumes:
      - ./docker/test_httpmq.yaml:/httpmq.yaml
