/*
httpmq

HTTP/2 based message broker built around NATS JetStream

API version: v0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// ManagementJSStreamParam struct for ManagementJSStreamParam
type ManagementJSStreamParam struct {
	// MaxAge is the max duration (ns) the stream will store a message  Messages breaching the limit will be removed.
	MaxAge *int64 `json:"max_age,omitempty"`
	// MaxBytes is the max number of message bytes the stream will store.  Oldest messages are removed once limit breached.
	MaxBytes *int64 `json:"max_bytes,omitempty"`
	// MaxConsumers is the max number of consumers allowed on the stream
	MaxConsumers *int64 `json:"max_consumers,omitempty"`
	// MaxMsgSize is the max size of a message allowed in this stream
	MaxMsgSize *int64 `json:"max_msg_size,omitempty"`
	// MaxMsgs is the max number of messages the stream will store.  Oldest messages are removed once limit breached.
	MaxMsgs *int64 `json:"max_msgs,omitempty"`
	// MaxMsgsPerSubject is the maximum number of subjects allowed on this stream
	MaxMsgsPerSubject *int64 `json:"max_msgs_per_subject,omitempty"`
	// Name is the stream name
	Name string `json:"name"`
	// Subjects is the list of subjects of interest for this stream
	Subjects *[]string `json:"subjects,omitempty"`
}

// NewManagementJSStreamParam instantiates a new ManagementJSStreamParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagementJSStreamParam(name string) *ManagementJSStreamParam {
	this := ManagementJSStreamParam{}
	this.Name = name
	return &this
}

// NewManagementJSStreamParamWithDefaults instantiates a new ManagementJSStreamParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagementJSStreamParamWithDefaults() *ManagementJSStreamParam {
	this := ManagementJSStreamParam{}
	return &this
}

// GetMaxAge returns the MaxAge field value if set, zero value otherwise.
func (o *ManagementJSStreamParam) GetMaxAge() int64 {
	if o == nil || o.MaxAge == nil {
		var ret int64
		return ret
	}
	return *o.MaxAge
}

// GetMaxAgeOk returns a tuple with the MaxAge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementJSStreamParam) GetMaxAgeOk() (*int64, bool) {
	if o == nil || o.MaxAge == nil {
		return nil, false
	}
	return o.MaxAge, true
}

// HasMaxAge returns a boolean if a field has been set.
func (o *ManagementJSStreamParam) HasMaxAge() bool {
	if o != nil && o.MaxAge != nil {
		return true
	}

	return false
}

// SetMaxAge gets a reference to the given int64 and assigns it to the MaxAge field.
func (o *ManagementJSStreamParam) SetMaxAge(v int64) {
	o.MaxAge = &v
}

// GetMaxBytes returns the MaxBytes field value if set, zero value otherwise.
func (o *ManagementJSStreamParam) GetMaxBytes() int64 {
	if o == nil || o.MaxBytes == nil {
		var ret int64
		return ret
	}
	return *o.MaxBytes
}

// GetMaxBytesOk returns a tuple with the MaxBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementJSStreamParam) GetMaxBytesOk() (*int64, bool) {
	if o == nil || o.MaxBytes == nil {
		return nil, false
	}
	return o.MaxBytes, true
}

// HasMaxBytes returns a boolean if a field has been set.
func (o *ManagementJSStreamParam) HasMaxBytes() bool {
	if o != nil && o.MaxBytes != nil {
		return true
	}

	return false
}

// SetMaxBytes gets a reference to the given int64 and assigns it to the MaxBytes field.
func (o *ManagementJSStreamParam) SetMaxBytes(v int64) {
	o.MaxBytes = &v
}

// GetMaxConsumers returns the MaxConsumers field value if set, zero value otherwise.
func (o *ManagementJSStreamParam) GetMaxConsumers() int64 {
	if o == nil || o.MaxConsumers == nil {
		var ret int64
		return ret
	}
	return *o.MaxConsumers
}

// GetMaxConsumersOk returns a tuple with the MaxConsumers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementJSStreamParam) GetMaxConsumersOk() (*int64, bool) {
	if o == nil || o.MaxConsumers == nil {
		return nil, false
	}
	return o.MaxConsumers, true
}

// HasMaxConsumers returns a boolean if a field has been set.
func (o *ManagementJSStreamParam) HasMaxConsumers() bool {
	if o != nil && o.MaxConsumers != nil {
		return true
	}

	return false
}

// SetMaxConsumers gets a reference to the given int64 and assigns it to the MaxConsumers field.
func (o *ManagementJSStreamParam) SetMaxConsumers(v int64) {
	o.MaxConsumers = &v
}

// GetMaxMsgSize returns the MaxMsgSize field value if set, zero value otherwise.
func (o *ManagementJSStreamParam) GetMaxMsgSize() int64 {
	if o == nil || o.MaxMsgSize == nil {
		var ret int64
		return ret
	}
	return *o.MaxMsgSize
}

// GetMaxMsgSizeOk returns a tuple with the MaxMsgSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementJSStreamParam) GetMaxMsgSizeOk() (*int64, bool) {
	if o == nil || o.MaxMsgSize == nil {
		return nil, false
	}
	return o.MaxMsgSize, true
}

// HasMaxMsgSize returns a boolean if a field has been set.
func (o *ManagementJSStreamParam) HasMaxMsgSize() bool {
	if o != nil && o.MaxMsgSize != nil {
		return true
	}

	return false
}

// SetMaxMsgSize gets a reference to the given int64 and assigns it to the MaxMsgSize field.
func (o *ManagementJSStreamParam) SetMaxMsgSize(v int64) {
	o.MaxMsgSize = &v
}

// GetMaxMsgs returns the MaxMsgs field value if set, zero value otherwise.
func (o *ManagementJSStreamParam) GetMaxMsgs() int64 {
	if o == nil || o.MaxMsgs == nil {
		var ret int64
		return ret
	}
	return *o.MaxMsgs
}

// GetMaxMsgsOk returns a tuple with the MaxMsgs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementJSStreamParam) GetMaxMsgsOk() (*int64, bool) {
	if o == nil || o.MaxMsgs == nil {
		return nil, false
	}
	return o.MaxMsgs, true
}

// HasMaxMsgs returns a boolean if a field has been set.
func (o *ManagementJSStreamParam) HasMaxMsgs() bool {
	if o != nil && o.MaxMsgs != nil {
		return true
	}

	return false
}

// SetMaxMsgs gets a reference to the given int64 and assigns it to the MaxMsgs field.
func (o *ManagementJSStreamParam) SetMaxMsgs(v int64) {
	o.MaxMsgs = &v
}

// GetMaxMsgsPerSubject returns the MaxMsgsPerSubject field value if set, zero value otherwise.
func (o *ManagementJSStreamParam) GetMaxMsgsPerSubject() int64 {
	if o == nil || o.MaxMsgsPerSubject == nil {
		var ret int64
		return ret
	}
	return *o.MaxMsgsPerSubject
}

// GetMaxMsgsPerSubjectOk returns a tuple with the MaxMsgsPerSubject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementJSStreamParam) GetMaxMsgsPerSubjectOk() (*int64, bool) {
	if o == nil || o.MaxMsgsPerSubject == nil {
		return nil, false
	}
	return o.MaxMsgsPerSubject, true
}

// HasMaxMsgsPerSubject returns a boolean if a field has been set.
func (o *ManagementJSStreamParam) HasMaxMsgsPerSubject() bool {
	if o != nil && o.MaxMsgsPerSubject != nil {
		return true
	}

	return false
}

// SetMaxMsgsPerSubject gets a reference to the given int64 and assigns it to the MaxMsgsPerSubject field.
func (o *ManagementJSStreamParam) SetMaxMsgsPerSubject(v int64) {
	o.MaxMsgsPerSubject = &v
}

// GetName returns the Name field value
func (o *ManagementJSStreamParam) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ManagementJSStreamParam) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ManagementJSStreamParam) SetName(v string) {
	o.Name = v
}

// GetSubjects returns the Subjects field value if set, zero value otherwise.
func (o *ManagementJSStreamParam) GetSubjects() []string {
	if o == nil || o.Subjects == nil {
		var ret []string
		return ret
	}
	return *o.Subjects
}

// GetSubjectsOk returns a tuple with the Subjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementJSStreamParam) GetSubjectsOk() (*[]string, bool) {
	if o == nil || o.Subjects == nil {
		return nil, false
	}
	return o.Subjects, true
}

// HasSubjects returns a boolean if a field has been set.
func (o *ManagementJSStreamParam) HasSubjects() bool {
	if o != nil && o.Subjects != nil {
		return true
	}

	return false
}

// SetSubjects gets a reference to the given []string and assigns it to the Subjects field.
func (o *ManagementJSStreamParam) SetSubjects(v []string) {
	o.Subjects = &v
}

func (o ManagementJSStreamParam) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.MaxAge != nil {
		toSerialize["max_age"] = o.MaxAge
	}
	if o.MaxBytes != nil {
		toSerialize["max_bytes"] = o.MaxBytes
	}
	if o.MaxConsumers != nil {
		toSerialize["max_consumers"] = o.MaxConsumers
	}
	if o.MaxMsgSize != nil {
		toSerialize["max_msg_size"] = o.MaxMsgSize
	}
	if o.MaxMsgs != nil {
		toSerialize["max_msgs"] = o.MaxMsgs
	}
	if o.MaxMsgsPerSubject != nil {
		toSerialize["max_msgs_per_subject"] = o.MaxMsgsPerSubject
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Subjects != nil {
		toSerialize["subjects"] = o.Subjects
	}
	return json.Marshal(toSerialize)
}

type NullableManagementJSStreamParam struct {
	value *ManagementJSStreamParam
	isSet bool
}

func (v NullableManagementJSStreamParam) Get() *ManagementJSStreamParam {
	return v.value
}

func (v *NullableManagementJSStreamParam) Set(val *ManagementJSStreamParam) {
	v.value = val
	v.isSet = true
}

func (v NullableManagementJSStreamParam) IsSet() bool {
	return v.isSet
}

func (v *NullableManagementJSStreamParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagementJSStreamParam(val *ManagementJSStreamParam) *NullableManagementJSStreamParam {
	return &NullableManagementJSStreamParam{value: val, isSet: true}
}

func (v NullableManagementJSStreamParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagementJSStreamParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
