/*
httpmq

HTTP/2 based message broker built around NATS JetStream

API version: v0.2.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// ApisAPIRestReqStreamSubjects struct for ApisAPIRestReqStreamSubjects
type ApisAPIRestReqStreamSubjects struct {
	// Subjects the list of new subject this stream will listen to
	Subjects []string `json:"subjects"`
}

// NewApisAPIRestReqStreamSubjects instantiates a new ApisAPIRestReqStreamSubjects object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApisAPIRestReqStreamSubjects(subjects []string) *ApisAPIRestReqStreamSubjects {
	this := ApisAPIRestReqStreamSubjects{}
	this.Subjects = subjects
	return &this
}

// NewApisAPIRestReqStreamSubjectsWithDefaults instantiates a new ApisAPIRestReqStreamSubjects object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApisAPIRestReqStreamSubjectsWithDefaults() *ApisAPIRestReqStreamSubjects {
	this := ApisAPIRestReqStreamSubjects{}
	return &this
}

// GetSubjects returns the Subjects field value
func (o *ApisAPIRestReqStreamSubjects) GetSubjects() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Subjects
}

// GetSubjectsOk returns a tuple with the Subjects field value
// and a boolean to check if the value has been set.
func (o *ApisAPIRestReqStreamSubjects) GetSubjectsOk() (*[]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subjects, true
}

// SetSubjects sets field value
func (o *ApisAPIRestReqStreamSubjects) SetSubjects(v []string) {
	o.Subjects = v
}

func (o ApisAPIRestReqStreamSubjects) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["subjects"] = o.Subjects
	}
	return json.Marshal(toSerialize)
}

type NullableApisAPIRestReqStreamSubjects struct {
	value *ApisAPIRestReqStreamSubjects
	isSet bool
}

func (v NullableApisAPIRestReqStreamSubjects) Get() *ApisAPIRestReqStreamSubjects {
	return v.value
}

func (v *NullableApisAPIRestReqStreamSubjects) Set(val *ApisAPIRestReqStreamSubjects) {
	v.value = val
	v.isSet = true
}

func (v NullableApisAPIRestReqStreamSubjects) IsSet() bool {
	return v.isSet
}

func (v *NullableApisAPIRestReqStreamSubjects) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApisAPIRestReqStreamSubjects(val *ApisAPIRestReqStreamSubjects) *NullableApisAPIRestReqStreamSubjects {
	return &NullableApisAPIRestReqStreamSubjects{value: val, isSet: true}
}

func (v NullableApisAPIRestReqStreamSubjects) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApisAPIRestReqStreamSubjects) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
