/*
httpmq

HTTP/2 based message broker built around NATS JetStream

API version: v0.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// ApisAPIRestRespStreamConfig struct for ApisAPIRestRespStreamConfig
type ApisAPIRestRespStreamConfig struct {
	// Description is an optional description of the stream
	Description *string `json:"description,omitempty"`
	// MaxBytes is the max duration (ns) the stream will store a message  Messages breaching the limit will be removed.
	MaxAge int64 `json:"max_age"`
	// MaxBytes is the max number of message bytes the stream will store.  Oldest messages are removed once limit breached.
	MaxBytes int64 `json:"max_bytes"`
	// MaxConsumers is the max number of consumers allowed on the stream
	MaxConsumers int64 `json:"max_consumers"`
	// MaxMsgSize is the max size of a message allowed in this stream
	MaxMsgSize *int64 `json:"max_msg_size,omitempty"`
	// MaxMsgs is the max number of messages the stream will store.  Oldest messages are removed once limit breached.
	MaxMsgs int64 `json:"max_msgs"`
	// MaxMsgsPerSubject is the maximum number of subjects allowed on this stream
	MaxMsgsPerSubject int64 `json:"max_msgs_per_subject"`
	// Name is the stream name
	Name string `json:"name"`
	// Subjects is the list subjects this stream is listening on
	Subjects *[]string `json:"subjects,omitempty"`
}

// NewApisAPIRestRespStreamConfig instantiates a new ApisAPIRestRespStreamConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApisAPIRestRespStreamConfig(maxAge int64, maxBytes int64, maxConsumers int64, maxMsgs int64, maxMsgsPerSubject int64, name string) *ApisAPIRestRespStreamConfig {
	this := ApisAPIRestRespStreamConfig{}
	this.MaxAge = maxAge
	this.MaxBytes = maxBytes
	this.MaxConsumers = maxConsumers
	this.MaxMsgs = maxMsgs
	this.MaxMsgsPerSubject = maxMsgsPerSubject
	this.Name = name
	return &this
}

// NewApisAPIRestRespStreamConfigWithDefaults instantiates a new ApisAPIRestRespStreamConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApisAPIRestRespStreamConfigWithDefaults() *ApisAPIRestRespStreamConfig {
	this := ApisAPIRestRespStreamConfig{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ApisAPIRestRespStreamConfig) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApisAPIRestRespStreamConfig) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ApisAPIRestRespStreamConfig) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ApisAPIRestRespStreamConfig) SetDescription(v string) {
	o.Description = &v
}

// GetMaxAge returns the MaxAge field value
func (o *ApisAPIRestRespStreamConfig) GetMaxAge() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MaxAge
}

// GetMaxAgeOk returns a tuple with the MaxAge field value
// and a boolean to check if the value has been set.
func (o *ApisAPIRestRespStreamConfig) GetMaxAgeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxAge, true
}

// SetMaxAge sets field value
func (o *ApisAPIRestRespStreamConfig) SetMaxAge(v int64) {
	o.MaxAge = v
}

// GetMaxBytes returns the MaxBytes field value
func (o *ApisAPIRestRespStreamConfig) GetMaxBytes() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MaxBytes
}

// GetMaxBytesOk returns a tuple with the MaxBytes field value
// and a boolean to check if the value has been set.
func (o *ApisAPIRestRespStreamConfig) GetMaxBytesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxBytes, true
}

// SetMaxBytes sets field value
func (o *ApisAPIRestRespStreamConfig) SetMaxBytes(v int64) {
	o.MaxBytes = v
}

// GetMaxConsumers returns the MaxConsumers field value
func (o *ApisAPIRestRespStreamConfig) GetMaxConsumers() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MaxConsumers
}

// GetMaxConsumersOk returns a tuple with the MaxConsumers field value
// and a boolean to check if the value has been set.
func (o *ApisAPIRestRespStreamConfig) GetMaxConsumersOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxConsumers, true
}

// SetMaxConsumers sets field value
func (o *ApisAPIRestRespStreamConfig) SetMaxConsumers(v int64) {
	o.MaxConsumers = v
}

// GetMaxMsgSize returns the MaxMsgSize field value if set, zero value otherwise.
func (o *ApisAPIRestRespStreamConfig) GetMaxMsgSize() int64 {
	if o == nil || o.MaxMsgSize == nil {
		var ret int64
		return ret
	}
	return *o.MaxMsgSize
}

// GetMaxMsgSizeOk returns a tuple with the MaxMsgSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApisAPIRestRespStreamConfig) GetMaxMsgSizeOk() (*int64, bool) {
	if o == nil || o.MaxMsgSize == nil {
		return nil, false
	}
	return o.MaxMsgSize, true
}

// HasMaxMsgSize returns a boolean if a field has been set.
func (o *ApisAPIRestRespStreamConfig) HasMaxMsgSize() bool {
	if o != nil && o.MaxMsgSize != nil {
		return true
	}

	return false
}

// SetMaxMsgSize gets a reference to the given int64 and assigns it to the MaxMsgSize field.
func (o *ApisAPIRestRespStreamConfig) SetMaxMsgSize(v int64) {
	o.MaxMsgSize = &v
}

// GetMaxMsgs returns the MaxMsgs field value
func (o *ApisAPIRestRespStreamConfig) GetMaxMsgs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MaxMsgs
}

// GetMaxMsgsOk returns a tuple with the MaxMsgs field value
// and a boolean to check if the value has been set.
func (o *ApisAPIRestRespStreamConfig) GetMaxMsgsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxMsgs, true
}

// SetMaxMsgs sets field value
func (o *ApisAPIRestRespStreamConfig) SetMaxMsgs(v int64) {
	o.MaxMsgs = v
}

// GetMaxMsgsPerSubject returns the MaxMsgsPerSubject field value
func (o *ApisAPIRestRespStreamConfig) GetMaxMsgsPerSubject() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MaxMsgsPerSubject
}

// GetMaxMsgsPerSubjectOk returns a tuple with the MaxMsgsPerSubject field value
// and a boolean to check if the value has been set.
func (o *ApisAPIRestRespStreamConfig) GetMaxMsgsPerSubjectOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxMsgsPerSubject, true
}

// SetMaxMsgsPerSubject sets field value
func (o *ApisAPIRestRespStreamConfig) SetMaxMsgsPerSubject(v int64) {
	o.MaxMsgsPerSubject = v
}

// GetName returns the Name field value
func (o *ApisAPIRestRespStreamConfig) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ApisAPIRestRespStreamConfig) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ApisAPIRestRespStreamConfig) SetName(v string) {
	o.Name = v
}

// GetSubjects returns the Subjects field value if set, zero value otherwise.
func (o *ApisAPIRestRespStreamConfig) GetSubjects() []string {
	if o == nil || o.Subjects == nil {
		var ret []string
		return ret
	}
	return *o.Subjects
}

// GetSubjectsOk returns a tuple with the Subjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApisAPIRestRespStreamConfig) GetSubjectsOk() (*[]string, bool) {
	if o == nil || o.Subjects == nil {
		return nil, false
	}
	return o.Subjects, true
}

// HasSubjects returns a boolean if a field has been set.
func (o *ApisAPIRestRespStreamConfig) HasSubjects() bool {
	if o != nil && o.Subjects != nil {
		return true
	}

	return false
}

// SetSubjects gets a reference to the given []string and assigns it to the Subjects field.
func (o *ApisAPIRestRespStreamConfig) SetSubjects(v []string) {
	o.Subjects = &v
}

func (o ApisAPIRestRespStreamConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["max_age"] = o.MaxAge
	}
	if true {
		toSerialize["max_bytes"] = o.MaxBytes
	}
	if true {
		toSerialize["max_consumers"] = o.MaxConsumers
	}
	if o.MaxMsgSize != nil {
		toSerialize["max_msg_size"] = o.MaxMsgSize
	}
	if true {
		toSerialize["max_msgs"] = o.MaxMsgs
	}
	if true {
		toSerialize["max_msgs_per_subject"] = o.MaxMsgsPerSubject
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Subjects != nil {
		toSerialize["subjects"] = o.Subjects
	}
	return json.Marshal(toSerialize)
}

type NullableApisAPIRestRespStreamConfig struct {
	value *ApisAPIRestRespStreamConfig
	isSet bool
}

func (v NullableApisAPIRestRespStreamConfig) Get() *ApisAPIRestRespStreamConfig {
	return v.value
}

func (v *NullableApisAPIRestRespStreamConfig) Set(val *ApisAPIRestRespStreamConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableApisAPIRestRespStreamConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableApisAPIRestRespStreamConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApisAPIRestRespStreamConfig(val *ApisAPIRestRespStreamConfig) *NullableApisAPIRestRespStreamConfig {
	return &NullableApisAPIRestRespStreamConfig{value: val, isSet: true}
}

func (v NullableApisAPIRestRespStreamConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApisAPIRestRespStreamConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
