/*
httpmq

HTTP/2 based message broker built around NATS JetStream

API version: v0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// ApisAPIRestRespStreamInfo struct for ApisAPIRestRespStreamInfo
type ApisAPIRestRespStreamInfo struct {
	Config ApisAPIRestRespStreamConfig `json:"config"`
	// Created is the stream creation timestamp
	Created string                     `json:"created"`
	State   ApisAPIRestRespStreamState `json:"state"`
}

// NewApisAPIRestRespStreamInfo instantiates a new ApisAPIRestRespStreamInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApisAPIRestRespStreamInfo(config ApisAPIRestRespStreamConfig, created string, state ApisAPIRestRespStreamState) *ApisAPIRestRespStreamInfo {
	this := ApisAPIRestRespStreamInfo{}
	this.Config = config
	this.Created = created
	this.State = state
	return &this
}

// NewApisAPIRestRespStreamInfoWithDefaults instantiates a new ApisAPIRestRespStreamInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApisAPIRestRespStreamInfoWithDefaults() *ApisAPIRestRespStreamInfo {
	this := ApisAPIRestRespStreamInfo{}
	return &this
}

// GetConfig returns the Config field value
func (o *ApisAPIRestRespStreamInfo) GetConfig() ApisAPIRestRespStreamConfig {
	if o == nil {
		var ret ApisAPIRestRespStreamConfig
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *ApisAPIRestRespStreamInfo) GetConfigOk() (*ApisAPIRestRespStreamConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *ApisAPIRestRespStreamInfo) SetConfig(v ApisAPIRestRespStreamConfig) {
	o.Config = v
}

// GetCreated returns the Created field value
func (o *ApisAPIRestRespStreamInfo) GetCreated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *ApisAPIRestRespStreamInfo) GetCreatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *ApisAPIRestRespStreamInfo) SetCreated(v string) {
	o.Created = v
}

// GetState returns the State field value
func (o *ApisAPIRestRespStreamInfo) GetState() ApisAPIRestRespStreamState {
	if o == nil {
		var ret ApisAPIRestRespStreamState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ApisAPIRestRespStreamInfo) GetStateOk() (*ApisAPIRestRespStreamState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ApisAPIRestRespStreamInfo) SetState(v ApisAPIRestRespStreamState) {
	o.State = v
}

func (o ApisAPIRestRespStreamInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["config"] = o.Config
	}
	if true {
		toSerialize["created"] = o.Created
	}
	if true {
		toSerialize["state"] = o.State
	}
	return json.Marshal(toSerialize)
}

type NullableApisAPIRestRespStreamInfo struct {
	value *ApisAPIRestRespStreamInfo
	isSet bool
}

func (v NullableApisAPIRestRespStreamInfo) Get() *ApisAPIRestRespStreamInfo {
	return v.value
}

func (v *NullableApisAPIRestRespStreamInfo) Set(val *ApisAPIRestRespStreamInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableApisAPIRestRespStreamInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableApisAPIRestRespStreamInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApisAPIRestRespStreamInfo(val *ApisAPIRestRespStreamInfo) *NullableApisAPIRestRespStreamInfo {
	return &NullableApisAPIRestRespStreamInfo{value: val, isSet: true}
}

func (v NullableApisAPIRestRespStreamInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApisAPIRestRespStreamInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
