/*
httpmq

HTTP/2 based message broker built around NATS JetStream

API version: v0.4.0-rc.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// GoutilsRestAPIBaseResponse struct for GoutilsRestAPIBaseResponse
type GoutilsRestAPIBaseResponse struct {
	Error *GoutilsErrorDetail `json:"error,omitempty"`
	// RequestID gives the request ID to match against logs
	RequestId string `json:"request_id"`
	// Success indicates whether the request was successful
	Success bool `json:"success"`
}

// NewGoutilsRestAPIBaseResponse instantiates a new GoutilsRestAPIBaseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoutilsRestAPIBaseResponse(requestId string, success bool) *GoutilsRestAPIBaseResponse {
	this := GoutilsRestAPIBaseResponse{}
	this.RequestId = requestId
	this.Success = success
	return &this
}

// NewGoutilsRestAPIBaseResponseWithDefaults instantiates a new GoutilsRestAPIBaseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoutilsRestAPIBaseResponseWithDefaults() *GoutilsRestAPIBaseResponse {
	this := GoutilsRestAPIBaseResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GoutilsRestAPIBaseResponse) GetError() GoutilsErrorDetail {
	if o == nil || o.Error == nil {
		var ret GoutilsErrorDetail
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoutilsRestAPIBaseResponse) GetErrorOk() (*GoutilsErrorDetail, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GoutilsRestAPIBaseResponse) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given GoutilsErrorDetail and assigns it to the Error field.
func (o *GoutilsRestAPIBaseResponse) SetError(v GoutilsErrorDetail) {
	o.Error = &v
}

// GetRequestId returns the RequestId field value
func (o *GoutilsRestAPIBaseResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *GoutilsRestAPIBaseResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *GoutilsRestAPIBaseResponse) SetRequestId(v string) {
	o.RequestId = v
}

// GetSuccess returns the Success field value
func (o *GoutilsRestAPIBaseResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *GoutilsRestAPIBaseResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *GoutilsRestAPIBaseResponse) SetSuccess(v bool) {
	o.Success = v
}

func (o GoutilsRestAPIBaseResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	if true {
		toSerialize["request_id"] = o.RequestId
	}
	if true {
		toSerialize["success"] = o.Success
	}
	return json.Marshal(toSerialize)
}

type NullableGoutilsRestAPIBaseResponse struct {
	value *GoutilsRestAPIBaseResponse
	isSet bool
}

func (v NullableGoutilsRestAPIBaseResponse) Get() *GoutilsRestAPIBaseResponse {
	return v.value
}

func (v *NullableGoutilsRestAPIBaseResponse) Set(val *GoutilsRestAPIBaseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGoutilsRestAPIBaseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGoutilsRestAPIBaseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoutilsRestAPIBaseResponse(val *GoutilsRestAPIBaseResponse) *NullableGoutilsRestAPIBaseResponse {
	return &NullableGoutilsRestAPIBaseResponse{value: val, isSet: true}
}

func (v NullableGoutilsRestAPIBaseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoutilsRestAPIBaseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
