/*
httpmq

HTTP/2 based message broker built around NATS JetStream

API version: v0.2.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// DataplaneAckSeqNum struct for DataplaneAckSeqNum
type DataplaneAckSeqNum struct {
	// Consumer is the JetStream message sequence number for this consumer
	Consumer int64 `json:"consumer"`
	// Stream is the JetStream message sequence number for this stream
	Stream int64 `json:"stream"`
}

// NewDataplaneAckSeqNum instantiates a new DataplaneAckSeqNum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataplaneAckSeqNum(consumer int64, stream int64) *DataplaneAckSeqNum {
	this := DataplaneAckSeqNum{}
	this.Consumer = consumer
	this.Stream = stream
	return &this
}

// NewDataplaneAckSeqNumWithDefaults instantiates a new DataplaneAckSeqNum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataplaneAckSeqNumWithDefaults() *DataplaneAckSeqNum {
	this := DataplaneAckSeqNum{}
	return &this
}

// GetConsumer returns the Consumer field value
func (o *DataplaneAckSeqNum) GetConsumer() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Consumer
}

// GetConsumerOk returns a tuple with the Consumer field value
// and a boolean to check if the value has been set.
func (o *DataplaneAckSeqNum) GetConsumerOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Consumer, true
}

// SetConsumer sets field value
func (o *DataplaneAckSeqNum) SetConsumer(v int64) {
	o.Consumer = v
}

// GetStream returns the Stream field value
func (o *DataplaneAckSeqNum) GetStream() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Stream
}

// GetStreamOk returns a tuple with the Stream field value
// and a boolean to check if the value has been set.
func (o *DataplaneAckSeqNum) GetStreamOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stream, true
}

// SetStream sets field value
func (o *DataplaneAckSeqNum) SetStream(v int64) {
	o.Stream = v
}

func (o DataplaneAckSeqNum) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["consumer"] = o.Consumer
	}
	if true {
		toSerialize["stream"] = o.Stream
	}
	return json.Marshal(toSerialize)
}

type NullableDataplaneAckSeqNum struct {
	value *DataplaneAckSeqNum
	isSet bool
}

func (v NullableDataplaneAckSeqNum) Get() *DataplaneAckSeqNum {
	return v.value
}

func (v *NullableDataplaneAckSeqNum) Set(val *DataplaneAckSeqNum) {
	v.value = val
	v.isSet = true
}

func (v NullableDataplaneAckSeqNum) IsSet() bool {
	return v.isSet
}

func (v *NullableDataplaneAckSeqNum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataplaneAckSeqNum(val *DataplaneAckSeqNum) *NullableDataplaneAckSeqNum {
	return &NullableDataplaneAckSeqNum{value: val, isSet: true}
}

func (v NullableDataplaneAckSeqNum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataplaneAckSeqNum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
