/*
httpmq

HTTP/2 based message broker built around NATS JetStream

API version: v0.1.2-rc.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// ApisAPIRestRespAllJetStreams struct for ApisAPIRestRespAllJetStreams
type ApisAPIRestRespAllJetStreams struct {
	Error *ApisErrorDetail `json:"error,omitempty"`
	// Streams the set of stream details mapped against its names
	Streams *map[string]ApisAPIRestRespStreamInfo `json:"streams,omitempty"`
	// Success indicates whether the request was successful
	Success bool `json:"success"`
}

// NewApisAPIRestRespAllJetStreams instantiates a new ApisAPIRestRespAllJetStreams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApisAPIRestRespAllJetStreams(success bool) *ApisAPIRestRespAllJetStreams {
	this := ApisAPIRestRespAllJetStreams{}
	this.Success = success
	return &this
}

// NewApisAPIRestRespAllJetStreamsWithDefaults instantiates a new ApisAPIRestRespAllJetStreams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApisAPIRestRespAllJetStreamsWithDefaults() *ApisAPIRestRespAllJetStreams {
	this := ApisAPIRestRespAllJetStreams{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ApisAPIRestRespAllJetStreams) GetError() ApisErrorDetail {
	if o == nil || o.Error == nil {
		var ret ApisErrorDetail
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApisAPIRestRespAllJetStreams) GetErrorOk() (*ApisErrorDetail, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ApisAPIRestRespAllJetStreams) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given ApisErrorDetail and assigns it to the Error field.
func (o *ApisAPIRestRespAllJetStreams) SetError(v ApisErrorDetail) {
	o.Error = &v
}

// GetStreams returns the Streams field value if set, zero value otherwise.
func (o *ApisAPIRestRespAllJetStreams) GetStreams() map[string]ApisAPIRestRespStreamInfo {
	if o == nil || o.Streams == nil {
		var ret map[string]ApisAPIRestRespStreamInfo
		return ret
	}
	return *o.Streams
}

// GetStreamsOk returns a tuple with the Streams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApisAPIRestRespAllJetStreams) GetStreamsOk() (*map[string]ApisAPIRestRespStreamInfo, bool) {
	if o == nil || o.Streams == nil {
		return nil, false
	}
	return o.Streams, true
}

// HasStreams returns a boolean if a field has been set.
func (o *ApisAPIRestRespAllJetStreams) HasStreams() bool {
	if o != nil && o.Streams != nil {
		return true
	}

	return false
}

// SetStreams gets a reference to the given map[string]ApisAPIRestRespStreamInfo and assigns it to the Streams field.
func (o *ApisAPIRestRespAllJetStreams) SetStreams(v map[string]ApisAPIRestRespStreamInfo) {
	o.Streams = &v
}

// GetSuccess returns the Success field value
func (o *ApisAPIRestRespAllJetStreams) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *ApisAPIRestRespAllJetStreams) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *ApisAPIRestRespAllJetStreams) SetSuccess(v bool) {
	o.Success = v
}

func (o ApisAPIRestRespAllJetStreams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	if o.Streams != nil {
		toSerialize["streams"] = o.Streams
	}
	if true {
		toSerialize["success"] = o.Success
	}
	return json.Marshal(toSerialize)
}

type NullableApisAPIRestRespAllJetStreams struct {
	value *ApisAPIRestRespAllJetStreams
	isSet bool
}

func (v NullableApisAPIRestRespAllJetStreams) Get() *ApisAPIRestRespAllJetStreams {
	return v.value
}

func (v *NullableApisAPIRestRespAllJetStreams) Set(val *ApisAPIRestRespAllJetStreams) {
	v.value = val
	v.isSet = true
}

func (v NullableApisAPIRestRespAllJetStreams) IsSet() bool {
	return v.isSet
}

func (v *NullableApisAPIRestRespAllJetStreams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApisAPIRestRespAllJetStreams(val *ApisAPIRestRespAllJetStreams) *NullableApisAPIRestRespAllJetStreams {
	return &NullableApisAPIRestRespAllJetStreams{value: val, isSet: true}
}

func (v NullableApisAPIRestRespAllJetStreams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApisAPIRestRespAllJetStreams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
