---
name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  golint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: golint
        uses: Jerome1337/golint-action@v1.0.2
        with:
          golint-path: "./..."

  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
          args: --timeout 3m0s

  test:
    runs-on: ubuntu-latest

    services:
      dev-nats:
        image: alwitt/nats-js:2.8.2-alpine
        ports:
          - 4222:4222
        options: --hostname dev-nats
      httpmq-mgmt:
        image: alwitt/cicd-support:httpmq-go.cicd.httpmq-0.4.1-rc.2-management
        ports:
          - 3000:3000
        env:
          LOG_LEVEL: info
          CONFIG_FILE: /httpmq.yaml
      httpmq-data:
        image: alwitt/cicd-support:httpmq-go.cicd.httpmq-0.4.1-rc.2-dataplane
        ports:
          - 3001:3000
        env:
          LOG_LEVEL: info
          CONFIG_FILE: /httpmq.yaml

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: go build -v -o httpmq-test-cli.bin .

      - name: Test
        run: |
          go test --count 1 -timeout 120s -short ./...
        env:
          HTTPMQ_MGMT_API_URL: http://127.0.0.1:3000
          HTTPMQ_DATA_API_URL: http://127.0.0.1:3001
